---
stages:
  - setup
  - lint
  - test
  - deploy
  - restart

setup:
  # necessary in order to use variable for image in test stage
  stage: setup
  script:
    - echo -n "HA_VERSION=" | cat - .HA_VERSION >> build.env
  artifacts:
    reports:
      dotenv: build.env

lint yaml:
  stage: lint
  image: sdesbure/yamllint
  before_script:
    - yamllint --version
  script:
    - yamllint .

test config:
  stage: test
  dependencies:
    - setup
  image:
    name: homeassistant/home-assistant:$HA_VERSION
    entrypoint: [""]
  script:
    - sh ./build/test.sh

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: alpine:latest
  before_script:
    - apk update && apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$SSH_HOST_KEY" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - sh ./build/deploy.sh

restart homeassistant:
  stage: restart
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - custom_components/**/*
        - "**/*.yaml"
  script:
    - apk update && apk add curl
    - sh ./build/restart.sh

redeploy docker:
  stage: restart
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - .HA_VERSION
  trigger: koen/docker
