stages:
  - build
  - test
  - deploy
  - restart
  - docker

build:
  # necessary in order to use variable for image in test stage
  stage: build
  script:
    - echo -n "HA_VERSION=" | cat - .HA_VERSION >> build.env
  artifacts:
    reports:
      dotenv: build.env

test:
  stage: test
  dependencies:
    - build
  image:
    name: homeassistant/home-assistant:$HA_VERSION
    entrypoint: [""]
  script:
    - sh ./build/test.sh

deploy:
  stage: deploy
  only:
    refs:
      - master
  script: 
    # https://unix.stackexchange.com/a/417661
    - apk update && apk add openssh sshpass
    - sh ./build/deploy.sh

restart:
  stage: restart
  only:
    refs:
      - master
  except:
    changes:
      - .HA_VERSION
  script:
    - apk update && apk add curl
    - sh ./build/restart.sh

docker:
  stage: docker
  only:
    refs:
      - master
    changes:
      - .HA_VERSION
  trigger: koen/docker
