stages:
  - init
  - test
  - deploy
  - restart
  - docker

init:
  # necessary in order to use variable for image in test stage
  stage: init
  script:
    - echo -n "HA_VERSION=" | cat - .HA_VERSION >> build.env
  artifacts:
    reports:
      dotenv: build.env

test:
  stage: test
  dependencies:
    - init
  image:
    name: homeassistant/home-assistant:$HA_VERSION
    entrypoint: [""]
  script:
    - sh ./build/test.sh

deploy:
  stage: deploy
  only:
    refs:
      - master
  script: 
    # https://unix.stackexchange.com/a/417661
    - apk update && apk add openssh sshpass
    - sh ./build/deploy.sh

restart:
  stage: restart
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - custom_components/**/*
        - "**/*.yaml"
  script:
    - apk update && apk add curl
    - sh ./build/restart.sh

docker:
  stage: docker
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - .HA_VERSION
  trigger: koen/docker
