language: python
python:
  - "3.7.4"
install:
  - pip3 install homeassistant
script:
  - hass --version
  - hass -c Configuration --script check_config
before_install:
- mv Configuration/travis_secrets.yaml Configuration/secrets.yaml
notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always