---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  packages: !include_dir_named packages
  legacy_templates: false

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - !secret http_proxy_ip

frontend:
  themes: !include_dir_merge_named themes

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  db_url: sqlite:///../data/home-assistant_v2.db
  purge_keep_days: 14

logger:
  default: info
  logs:
    roomba.roomba.Roomba: error

toon:
  client_id: !secret eneco_dev_key
  client_secret: !secret eneco_dev_secret

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chatid

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chatid

rflink:
  port: /dev/rflink

light:
  - platform: rflink
    automatic_add: false

sensor:
  - platform: rflink
    automatic_add: false
  - platform: time_date
    display_options:
      - date
      - time

binary_sensor:
  - platform: workday
    country: NL
