# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  packages: !include_dir_named packages
  legacy_templates: false

map:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

updater:
  reporting: false
  include_used_components: false

recorder:
  purge_keep_days: 14

logger:
  default: info
  logs:
    roomba.roomba.Roomba: error

sensor:
- platform: time_date
  display_options:
  - date
  - time

binary_sensor:
- platform: workday
  country: NL

toon:
  client_id: !secret eneco_dev_key
  client_secret: !secret eneco_dev_secret

telegram_bot:
- platform: polling
  api_key: !secret telegram_api
  allowed_chat_ids:
  - !secret telegram_chatid

notify:
- name: telegram
  platform: telegram
  chat_id: !secret telegram_chatid