input_boolean:
  activity_sleeping:
    icon: mdi:sleep

homeassistant:
  customize:
    input_boolean.activity_sleeping:
      friendly_name: Slapen

binary_sensor:
- platform: template
  sensors:
    activity_thuiswerken:
      friendly_name: Thuiswerken
      value_template: >
        {% set werkdag_start = states('input_datetime.heating_verwarming_aan_tijd_werkdag')[0:5] %}
        {% set weekend_start = states('input_datetime.heating_verwarming_aan_tijd_weekend')[0:5] %}
        {% if (
          is_state('binary_sensor.workday_sensor', 'on') and
          is_state('binary_sensor.presence_iemand_thuis', 'on') and 
          weekend_start <= states('sensor.time') <= werkdag_start
        ) %}
          true
        {% else %} 
          false
        {% endif %}

automation:
- id: activity_wakingup
  alias: Opstaan
  trigger:
  - platform: time
    at: 07:30
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.activity_sleeping
  initial_state: 'on'
