switch:
  - platform: mqtt
    name: "Boiler keuken"
    command_topic: "HW/sw/1/set"
    state_topic: "HW/sw/1/state"
    optimistic: false

automation:
  - alias: "Boiler keuken uit"
    initial_state: 'on'
    trigger:
      platform: time
      at: "00:00:00"
    action:
      service: switch.turn_off
      entity_id: switch.boiler_keuken
      
  - alias: "Boiler keuken aan (werkdag)"
    initial_state: 'on'
    trigger:
      platform: time
      at: "17:00:00"
    condition: 
      condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    action:
      service: switch.turn_on
      entity_id: switch.boiler_keuken
    
  - alias: "Boiler keuken aan (weekend)"
    initial_state: 'on'
    trigger:
      platform: time
      at: "08:00:00"
    condition: 
      condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'off'
    action:
      service: switch.turn_on
      entity_id: switch.boiler_keuken