cover:
  - platform: command_line
    covers:
      gordijn_voor:
        friendly_name: "Gordijn voor"
        command_open: "wget http://192.168.178.55:8080/moveup/CC:94:B6:F1:1D:DD --delete-after -qO-"
        command_close: "wget http://192.168.178.55:8080/movedown/CC:94:B6:F1:1D:DD --delete-after -qO-"
        command_stop: "wget http://192.168.178.55:8080/stop/CC:94:B6:F1:1D:DD --delete-after -qO-"
        command_position: "wget http://192.168.178.55:8080/setposition/CC:94:B6:F1:1D:DD/{position} --delete-after -qO-"
        command_state: "wget http://192.168.178.55:8080/getposition/CC:94:B6:F1:1D:DD --delete-after -qO-"

sensor:
  - platform: template
    sensors:
      positie_gordijn:
        friendly_name: "Gewenste positie gordijn"
        value_template: >
          {% if (is_state("input_boolean.slapen", "on")) %}
            0
          {% else %}
            {% if (
              states.sensor.current_time.state | int >= 2000 or 
              states.sensor.current_time.state | int < 700) 
            %}
              25
            {% elif (
              states.sensor.current_time.state | int >= 1600 and
              is_state("binary_sensor.donker_buiten", "on")) 
            %}
              35
            {% else %}
              {% if (
                states.climate.toon_van_eneco.attributes.current_temperature | int >= 21 and
                states.sensor.br_irradiance.state | int >= 300
              ) %}
                35
              {% else %}
                90
              {% endif %}
            {% endif %}
          {% endif %}
    
automation:
  - alias: "Stand gordijn"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.positie_gordijn
    action:
      service: cover.set_cover_position
      data_template:
        entity_id: cover.gordijn_voor
        position: "{{ states('sensor.positie_gordijn') }}"