homeassistant:
  customize:
    sensor.sonarr:
      hidden: true
    sensor.radarr:
      hidden: true

sensor:
  - platform: mqtt
    name: "Sonarr"
    state_topic: "downloads/sonarr"

  - platform: mqtt
    name: "Radarr"
    state_topic: "downloads/radarr"

automation:
  - alias: "Nieuwe download Sonarr"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.sonarr
    action:
      service: notify.telegram
      data_template:
        title: "Sonarr"
        message: "{{ states('sensor.sonarr') }}"

  - alias: "Nieuwe download Radarr"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.radarr
    action:
      service: notify.telegram
      data_template:
        title: "Radarr"
        message: "{{ states('sensor.radarr') }}"