input_boolean:
  verwarming_override:
    initial: off

input_datetime:
  verwarming_aan_tijd_werkdag:
    has_date: false
    has_time: true
  verwarming_aan_tijd_weekend:
    has_date: false
    has_time: true
  verwarming_uit_tijd:
    has_date: false
    has_time: true
    
sensor:
  - platform: template
    sensors:
      verwarming_aan_tijd:
        value_template: >-
          {% set current_time = (now().hour * 100) + now().minute %}
          {% set werkdag_start = state_attr("input_datetime.verwarming_aan_tijd_werkdag", "timestamp") | timestamp_custom('%H%M', false) | int %}
          {% set weekend_start = state_attr("input_datetime.verwarming_aan_tijd_weekend", "timestamp") | timestamp_custom('%H%M', false) | int %}
          {% set thuiswerken = is_state("binary_sensor.workday_sensor", "on") and is_state("binary_sensor.iemand_thuis", "on") and current_time >= weekend_start %}
          {% if is_state("binary_sensor.workday_sensor", "off") or thuiswerken -%}
            {{ weekend_start }}
          {% else %}
            {{ werkdag_start }}
          {% endif %}

binary_sensor:
  - platform: template
    sensors:
      verwarming_timeframe:
        value_template: >-
          {% set current_time = (now().hour * 100) + now().minute %}
          {% set timeframe_start = states("sensor.verwarming_aan_tijd") | int %}
          {% set timeframe_end = state_attr("input_datetime.verwarming_uit_tijd", "timestamp") | timestamp_custom('%H%M', false) | int %}
          {{ current_time >= timeframe_start and current_time <= timeframe_end }}
        entity_id: sensor.time

automation:
  - alias: "Verwarming override uit na thuiskomst"
    initial_state: on
    trigger:
      platform: state
      entity_id: binary_sensor.iemand_thuis
      to: 'on'
      for:
        minutes: 1
    condition:
      condition: state
      entity_id: input_boolean.verwarming_override
      state: 'on'
    action:
      service: input_boolean.turn_off
      entity_id: input_boolean.verwarming_override

  - alias: "Verwarming aan"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.iemand_thuis
        to: 'on'
      - platform: state
        entity_id: input_boolean.verwarming_override
        to: 'on'
      - platform: state
        entity_id: binary_sensor.verwarming_timeframe
        to: 'on'
      - platform: state
        entity_id: binary_sensor.should_preheat
        from: 'off'
        to: 'on'
    condition:
      condition: and
      conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.verwarming_timeframe
          state: 'on'
        - condition: state
          entity_id: binary_sensor.should_preheat
          state: 'on'
      - condition: state
        entity_id: input_boolean.slapen
        state: 'off'
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.iemand_thuis
          state: 'on'
        - condition: state
          entity_id: input_boolean.verwarming_override
          state: 'on'
    action:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.thermostat
          preset_mode: 'home'

  - alias: "Verwarming laag"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.iemand_thuis
        to: 'off'
      - platform: state
        entity_id: binary_sensor.verwarming_timeframe
        to: 'off'
    condition:
      condition: template
      value_template: '{{ is_state_attr("climate.thermostat", "preset_mode", "home") or is_state_attr("climate.thermostat", "preset_mode", "comfort") }}'
    action:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.thermostat
          preset_mode: 'sleep'

  - alias: "Verwarming uit"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: binary_sensor.iemand_thuis
      to: 'off'
      for:
        hours: 10
    condition:
      condition: state
      entity_id: input_boolean.verwarming_override
      state: 'off'
    action:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.thermostat
          preset_mode: 'away'