input_boolean:
  verwarming_override:
    initial: off

input_datetime:
  verwarming_aan_tijd:
    has_date: false
    has_time: true
  verwarming_uit_tijd:
    has_date: false
    has_time: true

binary_sensor:
  - platform: template
    sensors:
      verwarming_timeframe:
        value_template: >-
          {% set timeframe_start = states.input_datetime.verwarming_aan_tijd.attributes.timestamp | timestamp_custom('%H:%M', false) %}
          {% set timeframe_end = states.input_datetime.verwarming_uit_tijd.attributes.timestamp | timestamp_custom('%H:%M', false) %}
          {% set current_time = states.sensor.time.state %}
          {{ current_time >= timeframe_start and current_time <= timeframe_end }}

automation:
  - alias: "Verwarming override uit na thuiskomst"
    initial_state: on
    trigger:
      platform: state
      entity_id: binary_sensor.iemand_thuis
      to: 'on'
      for:
        minutes: 1
    condition:
      condition: state
      entity_id: input_boolean.verwarming_override
      state: 'on'
    action:
      service: input_boolean.turn_off
      entity_id: input_boolean.verwarming_override

  - alias: "Verwarming aan"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.iemand_thuis
        to: 'on'
      - platform: state
        entity_id: input_boolean.verwarming_override
        to: 'on'
      - platform: state
        entity_id: binary_sensor.verwarming_timeframe
        to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.verwarming_timeframe
        state: 'on'
      - condition: state
        entity_id: input_boolean.slapen
        state: 'off'
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.iemand_thuis
          state: 'on'
        - condition: state
          entity_id: input_boolean.verwarming_override
          state: 'on'
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.toon_thermostat
          operation_mode: "heat"

  - alias: "Verwarming laag"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.iemand_thuis
        to: 'off'
      - platform: state
        entity_id: binary_sensor.verwarming_timeframe
        to: 'off'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: climate.toon_thermostat
          state: 'Comfort'
        - condition: state
          entity_id: climate.toon_thermostat
          state: 'Home'
    action:
      service: climate.set_operation_mode
      data:
        entity_id: climate.toon_thermostat
        operation_mode: "cool"

  - alias: "Verwarming uit"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: binary_sensor.iemand_thuis
      to: 'off'
      for:
        hours: 10
    condition:
      condition: state
      entity_id: input_boolean.verwarming_override
      state: 'off'
    action:
      service: climate.set_operation_mode
      data: 
        entity_id: climate.toon_thermostat
        operation_mode: "eco"