input_boolean:
  verwarming_override:
    initial: off

automation:
  - alias: "Verwarming override uit na thuiskomst"
    initial_state: on
    trigger:
      platform: state
      entity_id: binary_sensor.iemand_thuis
      to: 'on'
      for:
        minutes: 1
    condition:
      condition: state
      entity_id: input_boolean.verwarming_override
      state: 'on'
    action:
      service: input_boolean.turn_off
      entity_id: input_boolean.verwarming_override

  - alias: "Verwarming aan"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.iemand_thuis
        to: 'on'
      - platform: state
        entity_id: input_boolean.verwarming_override
        to: 'on'
      - platform: time
        at: "09:00:00"
    condition:
      condition: and
      conditions:
      - condition: time
        after: "09:00:00"
        before: "22:30:00"
      - condition: state
        entity_id: input_boolean.slapen
        state: 'off'
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.iemand_thuis
          state: 'on'
        - condition: state
          entity_id: input_boolean.verwarming_override
          state: 'on'
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.toon_thermostat
          operation_mode: "heat"

  - alias: "Verwarming laag"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.iemand_thuis
        to: 'off'
      - platform: time
        at: "22:30:00"
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: climate.toon_thermostat
          state: 'Comfort'
          #is this state valid?
        - condition: state
          entity_id: climate.toon_thermostat
          state: 'Home'
          #is this state valid?
    action:
      service: climate.set_operation_mode
      data:
        entity_id: climate.toon_thermostat
        operation_mode: "cool"

  - alias: "Verwarming uit"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: binary_sensor.iemand_thuis
      to: 'off'
      for:
        hours: 10
    condition:
      condition: state
      entity_id: input_boolean.verwarming_override
      state: 'off'
    action:
      service: climate.set_operation_mode
      data: 
        entity_id: climate.toon_thermostat
        operation_mode: "eco"