sensor:
- platform: template
  sensors:
    home_cinema_state:
      friendly_name: Status home cinema
      value_template: >
        {% if (is_state_attr('media_player.denon_avr_x2100w', 'source', 'DVD') 
            and not is_state('media_player.living_room_tv', 'off')) %}
          {% if (is_state('media_player.living_room_tv', 'playing')) %}
            playing
          {% else %}
            paused
          {% endif %}
        {% else %}
          off
        {% endif %}
          
scene:
- name: home_cinema_playing
  entities:
    light.lamp_tv:
      state: on
      brightness: 30
    light.lamp_bank:
      state: on
      brightness: 30
    light.lamp_dressoir:
      state: on
      brightness: 30
    light.lamp_tafel_midden:
      state: on
      brightness: 15
    light.lamp_tafel_muur:
      state: on
      brightness: 15
    light.lamp_keuken_deur:
      state: off
    light.lamp_keuken_koelkast:
      state: off
    light.lamp_keuken_raam_links:
      state: off
    light.lamp_keuken_raam_rechts:
      state: off

- name: home_cinema_paused
  entities:
    light.lamp_tv:
      state: on
      brightness: 100
    light.lamp_bank:
      state: on
      brightness: 100
    light.lamp_dressoir:
      state: on
      brightness: 100
    light.lamp_tafel_midden:
      state: on
      brightness: 90
    light.lamp_tafel_muur:
      state: on
      brightness: 90
    light.lamp_keuken_deur:
      state: on
      brightness: 160
    light.lamp_keuken_koelkast:
      state: on
      brightness: 160
    light.lamp_keuken_raam_links:
      state: on
      brightness: 160
    light.lamp_keuken_raam_rechts:
      state: on
      brightness: 160

automation:
- id: home_cinema_ambilight_off
  alias: Ambilight uit
  initial_state: 'on'
  trigger: 
    platform: state
    entity_id: media_player.denon_avr_x2100w
    to: 'off'
  action:
    service: light.turn_off
    entity_id:
    - light.hue_play_1
    - light.hue_play_2

- id: home_cinema_playing
  alias: Film actief
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.donker_buiten
    to: 'on'
  - platform: state
    entity_id: sensor.home_cinema_state
    to: 'playing'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.donker_buiten
      state: 'on'
    - condition: state
      entity_id: sensor.home_cinema_state
      state: 'playing'
  action:
    service: scene.turn_on
    entity_id: scene.home_cinema_playing

- id: home_cinema_paused
  alias: Film gepauzeerd
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.donker_buiten
    to: 'on'
  - platform: state
    entity_id: sensor.home_cinema_state
    to: 'paused'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.donker_buiten
      state: 'on'
    - condition: state
      entity_id: sensor.home_cinema_state
      state: 'paused'
      for:
        seconds: 2
  action:
    service: scene.turn_on
    entity_id: scene.home_cinema_paused
