sensor:
  - platform: template
    sensors:
      home_cinema:
        value_template: >
          {% if (is_state_attr('media_player.denon_avr_x2100w', 'source', 'DVD') 
              and not is_state('media_player.watson', 'off')) %}
            {% if (is_state('media_player.watson', 'playing')) %}
              playing
            {% else %}
              paused
            {% endif %}
          {% else %}
            off
          {% endif %}
          
scene:
- name: "Licht film kijken"
  entities:
    light.lamp_tv:
      state: on
      brightness: 30
    light.lamp_bank:
      state: on
      brightness: 30
    light.lamp_dressoir:
      state: on
      brightness: 30
    light.lamp_tafel_midden:
      state: on
      brightness: 15
    light.lamp_tafel_muur:
      state: on
      brightness: 15
    light.lamp_keuken_deur:
      state: off
    light.lamp_keuken_koelkast:
      state: off
    light.lamp_keuken_raam_links:
      state: off
    light.lamp_keuken_raam_rechts:
      state: off

- name: "Licht film pauze"
  entities:
    light.lamp_tv:
      state: on
      brightness: 100
    light.lamp_bank:
      state: on
      brightness: 100
    light.lamp_dressoir:
      state: on
      brightness: 100
    light.lamp_tafel_midden:
      state: on
      brightness: 90
    light.lamp_tafel_muur:
      state: on
      brightness: 90
    light.lamp_keuken_deur:
      state: on
      brightness: 160
    light.lamp_keuken_koelkast:
      state: on
      brightness: 160
    light.lamp_keuken_raam_links:
      state: on
      brightness: 160
    light.lamp_keuken_raam_rechts:
      state: on
      brightness: 160

automation:
  - alias: "Ambilight uit"
    initial_state: 'on'
    trigger: 
      platform: state
      entity_id: media_player.denon_avr_x2100w
      to: 'off'
    action:
      service: light.turn_off
      entity_id:
        - light.hue_play_1
        - light.hue_play_2

  - alias: "Licht film kijken"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.donker_buiten
        to: 'on'
      - platform: state
        entity_id: sensor.home_cinema
        to: 'playing'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.donker_buiten
          state: 'on'
        - condition: state
          entity_id: sensor.home_cinema
          state: 'playing'
    action:
      service: scene.turn_on
      entity_id: scene.licht_film_kijken

  - alias: "Licht film pauze"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.donker_buiten
        to: 'on'
      - platform: state
        entity_id: sensor.home_cinema
        to: 'paused'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.donker_buiten
          state: 'on'
        - condition: state
          entity_id: sensor.home_cinema
          state: 'paused'
          for:
            seconds: 2
    action:
      service: scene.turn_on
      entity_id: scene.licht_film_pauze
