input_boolean:
  donker_override:
    initial: off

input_number:
  donker_buiten_threshold:
    name: "Donker buiten"
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "Lux"

binary_sensor:
- platform: template
  sensors:
    donker_buiten:
      value_template: >
        {% if (states("sensor.veranda_light_level") | int < states("input_number.donker_buiten_threshold") | int) %}
          true
        {% elif (is_state("input_boolean.donker_override", "on")) %}
          true
        {% else %}
          false
        {% endif %}
    opgestaan:
      value_template: >
        {% if (is_state("input_boolean.slapen", "off") and 
          as_timestamp(states.timer.beweging_overloop.last_updated) > as_timestamp(states.input_boolean.slapen.last_updated)) %}
          true
        {% else %}
          false
        {% endif %}

switch:
  - platform: flux
    lights:
      - light.lamp_gang
      - light.lamp_overloop
      - light.lamp_werkkamer
      - light.lamp_slaapkamer_links_voor
      - light.lamp_slaapkamer_links_midden
      - light.lamp_slaapkamer_links_achter
      - light.lamp_slaapkamer_rechts_voor
      - light.lamp_slaapkamer_rechts_midden
      - light.lamp_slaapkamer_rechts_achter
      - light.lamp_logeerkamer_links_voor
      - light.lamp_logeerkamer_links_achter
      - light.lamp_logeerkamer_rechts_voor
      - light.lamp_logeerkamer_rechts_achter
    name: 'Flux'
    start_time: '07:00'
    start_colortemp: 5000
    sunset_colortemp: 3400
    stop_colortemp: 1600
    mode: mired

scene:
- name: "Licht beneden normaal"
  entities:
    light.lamp_tv:
      state: on
      brightness: 220
    light.lamp_bank:
      state: on
      brightness: 220
    light.lamp_dressoir:
      state: on
      brightness: 220
    light.lamp_tafel_midden:
      state: on
      brightness: 200
    light.lamp_tafel_muur:
      state: on
      brightness: 200
    light.lamp_keuken_deur:
      state: on
      brightness: 220
    light.lamp_keuken_koelkast:
      state: on
      brightness: 220
    light.lamp_keuken_raam_links:
      state: on
      brightness: 220
    light.lamp_keuken_raam_rechts:
      state: on
      brightness: 220

- name: "Licht beneden uit"
  entities:
    light.lamp_tv: off
    light.lamp_bank: off
    light.lamp_dressoir: off
    light.lamp_tafel_midden: off
    light.lamp_tafel_muur: off
    light.lamp_keuken_deur: off
    light.lamp_keuken_koelkast: off
    light.lamp_keuken_raam_links: off
    light.lamp_keuken_raam_rechts: off
    light.lamp_gang: off

automation:
  - alias: "Licht beneden aan"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.donker_buiten
        to: 'on'
      - platform: state
        entity_id: binary_sensor.iemand_beneden
        to: 'on'
      - platform: state
        entity_id: sensor.home_cinema
        to: 'off'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.iemand_beneden
          state: 'on'
        - condition: state
          entity_id: binary_sensor.donker_buiten
          state: 'on'
        - condition: state
          entity_id: sensor.home_cinema
          state: 'off'
        - condition: state
          entity_id: input_boolean.slapen
          state: 'off'
    action:
      service: scene.turn_on
      entity_id: scene.licht_beneden_normaal

  - alias: "Licht uit"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.iemand_thuis
        to: 'off'
      - platform: state
        entity_id: binary_sensor.donker_buiten
        to: 'off'
      - platform: state
        entity_id: input_boolean.slapen
        to: 'on'
    action:
      service: light.turn_off
      entity_id: all

  - alias: "Licht beneden uit"
    initial_state: 'on'
    trigger: 
      platform: state
      entity_id: binary_sensor.iemand_beneden
      to: 'off'
      for:
        minutes: 5 
        #get off the damn couch and trigger the motion sensors
    condition: 
      condition: state
      entity_id: binary_sensor.iemand_thuis
      state: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.licht_beneden_uit

  - alias: "Licht gang aan"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.beweging_gang
    condition:
      condition: state
      entity_id: binary_sensor.donker_buiten
      state: 'on'
    action:
      service: light.turn_on
      entity_id: light.lamp_gang

  - alias: "Licht gang uit"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.beweging_gang
    action:
      service: light.turn_off
      entity_id: light.lamp_gang

  - alias: "Licht overloop aan"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.beweging_overloop
    condition:
      condition: state
      entity_id: binary_sensor.donker_buiten
      state: 'on'
    action:
      service: light.turn_on
      entity_id: light.lamp_overloop
        
  - alias: "Licht overloop uit"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.beweging_overloop
    action:
      service: light.turn_off
      entity_id: light.lamp_overloop

  - alias: "Licht werkkamer aan"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.beweging_werkkamer
    condition:
      condition: state
      entity_id: binary_sensor.donker_buiten
      state: 'on'
    action:
      service: light.turn_on
      entity_id: light.lamp_werkkamer

  - alias: "Licht werkkamer uit"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.beweging_werkkamer
    action:
      service: light.turn_off
      entity_id: light.lamp_werkkamer

  - alias: "Licht slaapkamer aan"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.beweging_slaapkamer
    condition:
      condition: state
      entity_id: binary_sensor.opgestaan
      state: 'on'
    action:
      service: light.turn_on
      entity_id: 
        - light.lamp_slaapkamer_links_voor
        - light.lamp_slaapkamer_links_midden
        - light.lamp_slaapkamer_links_achter
        - light.lamp_slaapkamer_rechts_voor
        - light.lamp_slaapkamer_rechts_midden
        - light.lamp_slaapkamer_rechts_achter

  - alias: "Licht slaapkamer uit"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.beweging_slaapkamer
    action:
      service: light.turn_off
      entity_id:
        - light.lamp_slaapkamer_links_voor
        - light.lamp_slaapkamer_links_midden
        - light.lamp_slaapkamer_links_achter
        - light.lamp_slaapkamer_rechts_voor
        - light.lamp_slaapkamer_rechts_midden
        - light.lamp_slaapkamer_rechts_achter

  - alias: "Licht logeerkamer aan"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.beweging_logeerkamer
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.donker_buiten
          state: 'on'
        - condition: state
          entity_id: input_boolean.slapen
          state: 'off'
    action:
      service: light.turn_on
      entity_id: 
        - light.lamp_logeerkamer_links_voor
        - light.lamp_logeerkamer_links_achter
        - light.lamp_logeerkamer_rechts_voor
        - light.lamp_logeerkamer_rechts_achter

  - alias: "Licht logeerkamer uit"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.beweging_logeerkamer
    action:
      service: light.turn_off
      entity_id:
        - light.lamp_logeerkamer_links_voor
        - light.lamp_logeerkamer_links_achter
        - light.lamp_logeerkamer_rechts_voor
        - light.lamp_logeerkamer_rechts_achter
