sensor:
  - platform: template
    sensors:
      temperatuur_buiten:
        unit_of_measurement: '°C'
        value_template: '{{ states("sensor.veranda_temperature") }}'
      hoogste_temperatuur_boven:
        unit_of_measurement: '°C'
        value_template: '{{ [states("sensor.overloop_temperature")|float, states("sensor.werkkamer_temperature")|float]|max }}'
      hoogste_temperatuur_beneden:
        unit_of_measurement: '°C'
        value_template: '{{ [states("sensor.gang_temperature")|float, states("sensor.woonkamer_temperature")|float, states("sensor.keuken_temperature")|float]|max }}'

binary_sensor:
  - platform: template
    sensors:
      temperatuur_boven_hoger_dan_buiten:
        value_template: '{{ states("sensor.hoogste_temperatuur_boven")|float > states("sensor.temperatuur_buiten")|float + 2 }}'
      temperatuur_beneden_hoger_dan_buiten:
        value_template: '{{ states("sensor.hoogste_temperatuur_beneden")|float > states("sensor.temperatuur_buiten")|float + 2 }}'

automation:
  - alias: "Notificatie boven ramen open"
    initial_state: on
    trigger:
      - platform: state
        entity_id: binary_sensor.iemand_thuis
        to: 'on'
      - platform: state
        entity_id: binary_sensor.temperatuur_boven_hoger_dan_buiten
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.hoogste_temperatuur_boven
          above: 22
        - condition: state
          entity_id: binary_sensor.iemand_thuis
          state: 'on'
        - condition: state
          entity_id: binary_sensor.temperatuur_boven_hoger_dan_buiten
          state: 'on'
        - condition: template
          value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.notificatie_boven_ramen_open.last_updated)) > 21600 }}'
        - condition: state
          entity_id: input_boolean.slapen
          state: 'off'
    action:
      - service: notify.telegram
        data:
          title: "Zet de ramen boven open"
          message: "Het is {{ states('sensor.hoogste_temperatuur_boven') }}°C boven en {{ states('sensor.temperatuur_buiten') }}°C buiten!"

  - alias: "Notificatie beneden ramen open"
    initial_state: on
    trigger:
      - platform: state
        entity_id: binary_sensor.iemand_thuis
        to: 'on'
      - platform: state
        entity_id: binary_sensor.temperatuur_beneden_hoger_dan_buiten
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.hoogste_temperatuur_beneden
          above: 22
        - condition: state
          entity_id: binary_sensor.iemand_thuis
          state: 'on'
        - condition: state
          entity_id: binary_sensor.temperatuur_beneden_hoger_dan_buiten
          state: 'on'
        - condition: template
          value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.notificatie_beneden_ramen_open.last_updated)) > 21600 }}'
        - condition: state
          entity_id: input_boolean.slapen
          state: 'off'
    action:
      - service: notify.telegram
        data:
          title: "Zet de ramen beneden open"
          message: "Het is {{ states('sensor.hoogste_temperatuur_beneden') }}°C beneden en {{ states('sensor.temperatuur_buiten') }}°C buiten!"