device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.178.1-64
    interval_seconds: 20
    home_interval: 8
    exclude:
      - 192.168.178.20
      - 192.168.178.23
      - 192.168.178.26
      - 192.168.178.30
      - 192.168.178.31
      - 192.168.178.38
      - 192.168.178.49

input_boolean:
  forceer_thuis:
    initial: off
  forceer_afwezig:
    initial: off

timer:
  beweging_keuken:
    duration: '00:05:00'
  beweging_woonkamer:
    duration: '00:10:00'
  beweging_gang:
    duration: '00:03:00'
  beweging_overloop:
    duration: '00:03:00'
  beweging_werkkamer:
    duration: '00:10:00'
    
binary_sensor:
  - platform: template
    sensors:
      iemand_thuis:
        value_template: >
          {% if (
            is_state('input_boolean.forceer_afwezig', 'off') and (
              is_state('input_boolean.forceer_thuis', 'on') or
              is_state('person.koen', 'home') or
              is_state('binary_sensor.iemand_beneden', 'on') or
              is_state('binary_sensor.iemand_boven', 'on'))) %}
            true
          {% else %} 
            false
          {% endif %}

  - platform: template
    sensors:
      iemand_beneden:
        value_template: >
          {% if (
            is_state('input_boolean.forceer_afwezig', 'off') and (
              is_state('media_player.denon_avr_x2100w', 'on') or
              is_state('timer.beweging_keuken', 'active') or
              is_state('timer.beweging_woonkamer', 'active') or
              is_state('timer.beweging_gang', 'active'))) %}
            true
          {% else %}
            false
          {% endif %}

  - platform: template
    sensors:
      iemand_boven:
        value_template: >
          {% if (
            is_state('input_boolean.forceer_afwezig', 'off') and (
              is_state('timer.beweging_overloop', 'active') or
              is_state('timer.beweging_werkkamer', 'active'))) %}
            true
          {% else %}
            false
          {% endif %}

automation:
  - alias: "Forceer thuis"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_boolean.forceer_thuis
      to: 'on'
    action:
      service: input_boolean.turn_off
      entity_id: input_boolean.forceer_afwezig

  - alias: "Forceer afwezig"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_boolean.forceer_afwezig
      to: 'on'
    action:
      service: input_boolean.turn_off
      entity_id: input_boolean.forceer_thuis

  - alias: "Beweging keuken"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: binary_sensor.keuken_motion
      to: 'on'
    action:
      service: timer.start
      entity_id: timer.beweging_keuken

  - alias: "Beweging woonkamer"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: binary_sensor.woonkamer_motion
      to: 'on'
    action:
      service: timer.start
      entity_id: timer.beweging_woonkamer

  - alias: "Beweging gang"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: binary_sensor.gang_motion
      to: 'on'
    action:
      service: timer.start
      entity_id: timer.beweging_gang
        

  - alias: "Beweging overloop"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: binary_sensor.overloop_motion
      to: 'on'
    action:
      service: timer.start
      entity_id: timer.beweging_overloop

  - alias: "Beweging werkkamer"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: binary_sensor.werkkamer_motion
      to: 'on'
    action:
      service: timer.start
      entity_id: timer.beweging_werkkamer