rest_command:
  travis_request:
    url: https://api.travis-ci.org/repo/peckham%2Fhomeassistant/requests
    method: POST
    content_type: application/json
    headers:
      authorization: !secret travis_auth
      accept: application/json
      Travis-API-Version: 3
    payload: '{{ request }}'

automation:
  - id: travis_check_config
    alias: Travis check config update"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.updater
        from: 'off'
        to: 'on'
    action:
      - service: rest_command.travis_request
        data:
          request: '{"request": {"branch":"master"}}'
