homeassistant:
  customize:
    sensor.weatherstation:
      hidden: true

sensor:
  - platform: rest
    resource: !secret weatherstation_url
    name: weatherstation
    json_attributes:
      - temperature
      - light
      - rain
    
  - platform: template
    sensors:
      temperatuur_veranda:
        friendly_name: "Temperatuur veranda"
        unit_of_measurement: "°C"
        value_template: >
          {% if not is_state('sensor.weatherstation', 'unavailable') and 
            states.sensor.weatherstation.attributes["temperature"] is defined %}
            {{ states.sensor.weatherstation.attributes["temperature"] }}
          {% else %}
            {{ states.sensor.temperatuur_veranda.state }}
          {% endif %}
      licht_veranda:
        friendly_name: "Licht veranda"
        unit_of_measurement: "%"
        value_template: >
          {% if not is_state('sensor.weatherstation', 'unavailable') and 
            states.sensor.weatherstation.attributes["light"] is defined %}
            {{ states.sensor.weatherstation.attributes["light"] }}
          {% else %}
            {{ states.sensor.licht_veranda.state }}
          {% endif %}
      regen_veranda:
        friendly_name: "Regen veranda"
        unit_of_measurement: "%"
        value_template: >
          {% if not is_state('sensor.weatherstation', 'unavailable') and 
            states.sensor.weatherstation.attributes["rain"] is defined %}
            {{ states.sensor.weatherstation.attributes["rain"] }}
          {% else %}
            {{ states.sensor.regen_veranda.state }}
          {% endif %}
          
binary_sensor:
  - platform: template
    sensors:
      weatherstation_online:
        friendly_name: "Weerstation bereikbaar"
        value_template: >
          {% if is_state('sensor.weatherstation', 'unavailable') %}
            false
          {% else %}
            true
          {% endif %}

automation:
  - alias: "Weerstation offline notificatie"
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: binary_sensor.weatherstation_online
      to: 'off'
      for:
        minutes: 20
    action:
      service: notify.telegram
      data:
        message: "Het weerstation is niet meer bereikbaar."