- alias: "Opstaan"
  trigger:
    platform: time
    at: "07:30:00"
  action:
    service: scene.turn_on
    entity_id: scene.opstaan

- alias: "Lichten aan"
  trigger:
    - platform: state
      entity_id: binary_sensor.donker_buiten
      to: 'on'
    - platform: state
      entity_id: binary_sensor.iemand_thuis
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.iemand_thuis
        state: 'on'
      - condition: state
        entity_id: binary_sensor.donker_buiten
        state: 'on'
      - condition: state
        entity_id: binary_sensor.film_kijken
        state: 'off'
      - condition: state
        entity_id: input_boolean.slapen
        state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.licht_normaal

- alias: "Lichten uit"
  trigger:
    - platform: state
      entity_id: binary_sensor.iemand_thuis
      to: 'off'
    - platform: state
      entity_id: binary_sensor.donker_buiten
      to: 'off'
  action:
    service: light.turn_off

- alias: "Verwarming aan"
  trigger:
    - platform: state
      entity_id: binary_sensor.iemand_thuis
      to: 'on'
    - platform: time
      at: "09:00:00"
  condition:
    condition: and
    conditions:
    - condition: time
      after: "07:00:00"
      before: "22:30:00"
    - condition: state
      entity_id: input_boolean.slapen
      state: 'off'
    - condition: state
      entity_id: binary_sensor.iemand_thuis
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.verwarming_normaal

- alias: "Verwarming laag"
  trigger:
    - platform: state
      entity_id: binary_sensor.iemand_thuis
      to: 'off'
    - platform: time
      at: "22:30:00"
  condition:
    condition: state
    entity_id: switch.verwarming_lang_afwezig
    state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.verwarming_kort_weg

- alias: "Verwarming uit"
  trigger:
    platform: state
    entity_id: binary_sensor.iemand_thuis
    to: 'off'
    for:
      hours: 10
  action:
    service: scene.turn_on
    entity_id: scene.verwarming_lang_weg

- alias: "Boiler keuken uit"
  trigger:
    platform: time
    at: "23:59:00"
  action:
    service: switch.turn_off
    entity_id: switch.boiler_keuken
    
- alias: "Boiler keuken aan (werkdag)"
  trigger:
    platform: time
    at: "17:00:00"
  condition: 
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.boiler_keuken
  
- alias: "Boiler keuken aan (weekend)"
  trigger:
    platform: time
    at: "08:00:00"
  condition: 
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.boiler_keuken

- alias: "Film kijken"
  trigger:
    platform: state
    entity_id: binary_sensor.film_kijken
    to: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.film_start
  
- alias: "Film gepauzeerd"
  trigger:
    platform: state
    entity_id: media_player.mycroft
    from: "playing"
  condition:
    condition: state
    entity_id: binary_sensor.donker_buiten
    state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.film_gepauzeerd
  
- alias: "Film gestart/hervat"
  trigger:
    platform: state
    entity_id: media_player.mycroft
    to: "playing"
  action:
    service: scene.turn_on
    entity_id: scene.film_actief
    
- alias: "Film gestopt"
  trigger:
    platform: state
    entity_id: binary_sensor.film_kijken
    from: 'on'
    to: 'off'
  condition:
    condition: state
    entity_id: binary_sensor.donker_buiten
    state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.licht_normaal

- alias: "Gordijn omlaag in namiddag"
  trigger:
    platform: time
    at: "17:00:00"
  action:
    service: cover.set_cover_position
    data:
      entity_id: cover.gordijn_voor
      position: 50
      