- id: hass_start
  alias: Start HomeAssistant
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      entity_id: switch.flux
    entity_id: switch.flux
    service: switch.turn_on
  initial_state: 'on'
- id: '1558982905019'
  alias: Opstaan
  trigger:
  - at: 07:30
    platform: time
  condition: []
  action:
  - data:
      entity_id: input_boolean.slapen
    service: input_boolean.turn_off
  initial_state: 'on'
