- platform: workday
  country: NL

- platform: template
  sensors:
    donker_buiten:
#      value_template: >
#        {% if (states.sun.sun.attributes.elevation | int < 20) %} 
#          true
#        {% elif ((states.sun.sun.attributes.elevation | int < 40) and 
#          (states.sensor.dark_sky_cloud_coverage.state | int > 50)) %} 
#          true
#        {% elif (states.sensor.dark_sky_cloud_coverage.state | int > 90) %} 
#          true
#        {% else %} 
#          false
#        {% endif %}
      value_template: >
        {% if (states.sun.sun.attributes.elevation | int < 5) %}
          true
        {% else %}
          false
        {% endif %}
      entity_id:
        - sun.sun
#        - sensor.dark_sky_cloud_coverage

- platform: template
  sensors:
    donker_buiten_test:
      value_template: >
        {% if (states.sensor.br_irradiance.state | int < 100) %}
          true
        {% else %} 
          false
        {% endif %}
      entity_id:
        - sensor.br_irradiance
        
- platform: template
  sensors:
    iemand_thuis:
      value_template: >
        {% if (is_state('device_tracker.huaweip10litefritzbox', 'home')) %}
          true
        {% else %} 
          false
        {% endif %}
      entity_id:
        - device_tracker.huaweip10litefritzbox
        
- platform: template
  sensors:
    film_kijken:
      value_template: >
        {% if (states.remote.tv_woonkamer.attributes.current_activity | lower == 'watch a movie') %}
          true
        {% else %}
          false
        {% endif %}
      entity_id:
        - remote.tv_woonkamer
