- platform: workday
  country: NL

- platform: template
  sensors:
    donker_buiten:
      value_template: >
        {% if (states.sensor.licht_veranda.state | int < states.input_number.donker_buiten_threshold.state | int) %}
          true
        {% elif (is_state('input_boolean.donker_override', 'on')) %}
          true
        {% else %}
          false
        {% endif %}

- platform: template
  sensors:
    tv_woonkamer_aan:
      value_template: >
        {% if (is_state('media_player.denon_avrx2100w', 'on')) %}
          true
        {% else %} 
          false
        {% endif %}
       
- platform: template
  sensors:
    film_kijken:
      value_template: >
        {% if (states.remote.tv_woonkamer.attributes.current_activity | lower == 'watch a movie') %}
          true
        {% else %}
          false
        {% endif %}
