- platform: workday
  country: NL

- platform: template
  sensors:
    donker_buiten:
#      value_template: >
#        {% if (states.sun.sun.attributes.elevation | int < 20) %} 
#          true
#        {% elif ((states.sun.sun.attributes.elevation | int < 40) and 
#          (states.sensor.dark_sky_cloud_coverage.state | int > 50)) %} 
#          true
#        {% elif (states.sensor.dark_sky_cloud_coverage.state | int > 90) %} 
#          true
#        {% else %} 
#          false
#        {% endif %}
      value_template: >
        {% if (states.sun.sun.attributes.elevation | int < 7) %}
          true
        {% else %}
          false
        {% endif %}
      entity_id:
        - sun.sun
#        - sensor.dark_sky_cloud_coverage

- platform: template
  sensors:
    donker_test:
      #value_template: >
      #  {% if (states.sensor.br_irradiance.state | int < 100) %}
      #    true
      #  {% else %} 
      #    false
      #  {% endif %}
      value_template: >
        {% if (states.sensor.exterior_lux.state | int < 500) %}
          true
        {% else %}
          false
        {% endif %}
      entity_id:
      #  - sensor.br_irradiance
        - sensor.exterior_lux

- platform: template
  sensors:
    schemer_test:
      value_template: >
        {% if (states.sensor.exterior_lux.state | int < 1250) %}
          true
        {% else %}
          false
        {% endif %}
      entity_id:
        - sensor.exterior_lux

- platform: template
  sensors:
    tv_woonkamer_aan:
      value_template: >
        {% if (is_state('remote.tv_woonkamer', 'on')) %}
          true
        {% else %} 
          false
        {% endif %}
      entity_id:
        - remote.tv_woonkamer
        
- platform: template
  sensors:
    iemand_thuis:
      value_template: >
        {% if (
          is_state('input_boolean.forceer_afwezig', 'off') and (
            is_state('input_boolean.forceer_thuis', 'on') or
            is_state('device_tracker.huaweip10litefritzbox', 'home') or
            is_state('binary_sensor.iemand_beneden', 'on') or
            is_state('binary_sensor.iemand_boven', 'on'))) %}
          true
        {% else %} 
          false
        {% endif %}
      entity_id:
        - input_boolean.forceer_afwezig
        - input_boolean.forceer_thuis
        - device_tracker.huaweip10litefritzbox
        - binary_sensor.iemand_beneden
        - binary_sensor.iemand_boven

- platform: template
  sensors:
    iemand_beneden:
      value_template: >
        {% if (
          is_state('input_boolean.forceer_afwezig', 'off') and (
            is_state('binary_sensor.tv_woonkamer_aan', 'on') or
            is_state('timer.beweging_keuken', 'active') or
            is_state('timer.beweging_woonkamer', 'active') or
            is_state('timer.beweging_gang', 'active'))) %}
          true
        {% else %}
          false
        {% endif %}
      entity_id:
        - input_boolean.forceer_afwezig
        - binary_sensor.tv_woonkamer_aan
        - timer.beweging_keuken
        - timer.beweging_woonkamer
        - timer.beweging_gang

- platform: template
  sensors:
    iemand_boven:
      value_template: >
        {% if (
          is_state('input_boolean.forceer_afwezig', 'off') and (
            is_state('timer.beweging_overloop', 'active') or
            is_state('timer.beweging_werkkamer', 'active'))) %}
          true
        {% else %}
          false
        {% endif %}
      entity_id:
        - input_boolean.forceer_afwezig
        - timer.beweging_overloop
        - timer.beweging_werkkamer
        
- platform: template
  sensors:
    film_kijken:
      value_template: >
        {% if (states.remote.tv_woonkamer.attributes.current_activity | lower == 'watch a movie') %}
          true
        {% else %}
          false
        {% endif %}
      entity_id:
        - remote.tv_woonkamer
