- platform: workday
  country: NL

- platform: template
  sensors:
    donker_buiten:
      value_template: >
        {% if (states.sun.sun.attributes.elevation | int < 10) %}
          true
        {% elif ((states.sun.sun.attributes.elevation | int < 15) and (states.sensor.dark_sky_cloud_coverage.state | int > 40)) %}
          true
        {% elif ((states.sun.sun.attributes.elevation | int < 20) and (states.sensor.dark_sky_cloud_coverage.state | int > 70)) %}
          true
        {% elif (states.sensor.dark_sky_cloud_coverage.state | int > 99) %}
          true
        {% else %}
          false
        {% endif %}

- platform: template
  sensors:
    tv_woonkamer_aan:
      value_template: >
        {% if (is_state('media_player.denon_avrx2100w', 'on')) %}
          true
        {% else %} 
          false
        {% endif %}
       
- platform: template
  sensors:
    film_kijken:
      value_template: >
        {% if (states.remote.tv_woonkamer.attributes.current_activity | lower == 'watch a movie') %}
          true
        {% else %}
          false
        {% endif %}
