- platform: workday
  country: NL

- platform: template
  sensors:
    donker_buiten:
#      value_template: >
#        {% if (states.sun.sun.attributes.elevation | int < 20) %} 
#          true
#        {% elif ((states.sun.sun.attributes.elevation | int < 40) and 
#          (states.sensor.dark_sky_cloud_coverage.state | int > 50)) %} 
#          true
#        {% elif (states.sensor.dark_sky_cloud_coverage.state | int > 90) %} 
#          true
#        {% else %} 
#          false
#        {% endif %}
      value_template: >
        {% if (states.sun.sun.attributes.elevation | int < 7) %}
          true
        {% else %}
          false
        {% endif %}
      entity_id:
        - sun.sun
#        - sensor.dark_sky_cloud_coverage

- platform: template
  sensors:
    donker_test:
      #value_template: >
      #  {% if (states.sensor.br_irradiance.state | int < 100) %}
      #    true
      #  {% else %} 
      #    false
      #  {% endif %}
      value_template: >
        {% if (states.sensor.lux | int < 500) %}
          true
        {% else %}
          false
        {% endif %}
      entity_id:
      #  - sensor.br_irradiance
        - sensor.lux

- platform: template
  sensors:
    schemer_test:
      value_template: >
        {% if (states.sensor.lux | int < 1000) %}
          true
        {% else %}
          false
        {% endif %}
      entity_id:
        - sensor.lux

- platform: template
  sensors:
    tv_woonkamer_aan:
      value_template: >
        {% if (is_state('remote.tv_woonkamer', 'on')) %}
          true
        {% else %} 
          false
        {% endif %}
      entity_id:
        - remote.tv_woonkamer
        
- platform: template
  sensors:
    iemand_thuis:
      value_template: >
        {% if (
          is_state('device_tracker.huaweip10litefritzbox', 'home') or
          is_state('device_tracker.gladosfritzbox', 'home') or
          is_state('sensor.tv_woonkamer_aan', 'on')) %}
          true
        {% else %} 
          false
        {% endif %}
      entity_id:
        - device_tracker.huaweip10litefritzbox
        
- platform: template
  sensors:
    film_kijken:
      value_template: >
        {% if (states.remote.tv_woonkamer.attributes.current_activity | lower == 'watch a movie') %}
          true
        {% else %}
          false
        {% endif %}
      entity_id:
        - remote.tv_woonkamer
