homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 6
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

zone:
  name: Work
  icon: 'mdi:pi-box'
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  radius: 90

logger:
  default: info
  logs:
    homeassistant.components.device_tracker.nmap_tracker: error
  
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  javascript_version: latest

# Enables a map showing the location of tracked devices
map:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:
  include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

recorder:
  purge_interval: 1
  purge_keep_days: 14

# Track the sun
sun:

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.178.1-64
    interval_seconds: 20
    home_interval: 8
    exclude:
      - 192.168.178.20
      - 192.168.178.23
      - 192.168.178.26
      - 192.168.178.30
      - 192.168.178.31

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: !secret mqtt_client_id
  username: !secret mqtt_username
  password: !secret mqtt_password

media_player:
  - platform: plex

remote:
  - platform: harmony
    name: "TV Woonkamer"
    host: 192.168.178.20
    scan_interval: 10

cover:
  - platform: mqtt
    name: "Gordijn voor"
    set_position_topic: "soma/shade/rise201/set"
    state_topic: "soma/shade/rise201/state"
    retain: false

input_boolean:
  #no initial values, handled by the recorder component
  slapen:
    icon: 'mdi:sleep'
  forceer_thuis:
    initial: off
  forceer_afwezig:
    initial: off
  verwarming_override:
    initial: off

input_datetime:
  laatste_beweging_keuken:
    has_date: true
    has_time: true
  laatste_beweging_werkkamer:
    has_date: true
    has_time: true
  laatste_beweging_gang:
    has_date: true
    has_time: true

panel_iframe: !include panels.yaml
sensor: !include sensors.yaml
light: !include lights.yaml 
switch: !include switches.yaml
group: !include groups.yaml
binary_sensor: !include binary_sensors.yaml
scene: !include scenes.yaml
automation: !include automations.yaml

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chatid

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chatid

toon:
  username: !secret eneco_user
  password: !secret eneco_pass

history_graph:
  temperature:
    name: "Temperatuur"
    hours_to_show: 3
    entities:
      - sensor.temperatuur_keuken
      - sensor.temperatuur_gang
      - sensor.temperatuur_werkkamer
      - sensor.current_temperature_toon
  lux:
    name: "Lichtniveau buiten"
    entities:
      - sensor.above_cloud_lux
      - sensor.exterior_lux
  lightlevels:
    name: "Lichtniveau binnen"
    hours_to_show: 3
    entities:
      - sensor.lichtniveau_keuken
      - sensor.lichtniveau_gang
      - sensor.lichtniveau_werkkamer