homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 6
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

updater:
  reporting: false
  include_used_components: false

zone:
  name: Work
  icon: 'mdi:pi-box'
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  radius: 90

# Enables a map showing the location of tracked devices
map:

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

recorder:
  purge_interval: 1
  purge_keep_days: 14

# Discover some devices automatically
discovery:

logger:
  default: info
  logs:
    homeassistant.components.device_tracker.nmap_tracker: error
    roomba.roomba.Roomba: error

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
panel_iframe: !include panels.yaml

binary_sensor:
- platform: workday
  country: NL
- platform: mystrom

input_boolean:
  slapen:
    icon: 'mdi:sleep'

toon:
  client_id: !secret eneco_dev_key
  client_secret: !secret eneco_dev_secret

hue:
  bridges:
    - host: 192.168.178.23
      allow_unreachable: true
      allow_hue_groups: false

remote:
  - platform: harmony
    name: "TV Woonkamer"
    host: 192.168.178.20
    scan_interval: 2

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chatid

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chatid