homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 6
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  packages: !include_dir_named packages

zone:
  name: Work
  icon: 'mdi:pi-box'
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  radius: 90

logger:
  default: info
  logs:
    homeassistant.components.device_tracker.nmap_tracker: error
  
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  javascript_version: latest

# Enables a map showing the location of tracked devices
map:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:
  include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

recorder:
  purge_interval: 1
  purge_keep_days: 14

# Track the sun
sun:

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: !secret mqtt_client_id
  username: !secret mqtt_username
  password: !secret mqtt_password

media_player:
  - platform: plex
    scan_interval: 2
  - platform: denon
    host: 192.168.178.27

remote:
  - platform: harmony
    name: "TV Woonkamer"
    host: 192.168.178.20
    scan_interval: 2

input_boolean:
  slapen:
    icon: 'mdi:sleep'
  donker_override:
    initial: off

input_number:
  donker_buiten_threshold:
    name: "Donker buiten"
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"

panel_iframe: !include panels.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
group: !include groups.yaml
binary_sensor: !include binary_sensors.yaml
scene: !include scenes.yaml
automation: !include automations.yaml

hue:
  bridges:
    - host: 192.168.178.23
      allow_unreachable: true

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chatid

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chatid

history_graph:
  temperature:
    name: "Temperatuur"
    hours_to_show: 3
    entities:
      - sensor.temperatuur_keuken
      - sensor.temperatuur_gang
      - sensor.temperatuur_werkkamer
      - sensor.temperatuur_woonkamer
      - sensor.temperatuur_overloop
      - sensor.current_temperature_toon
#  lux:
#    name: "Lichtniveau buiten"
#    entities:
#      - sensor.above_cloud_lux
#      - sensor.exterior_lux
  lightlevels:
    name: "Lichtniveau binnen"
    hours_to_show: 3
    entities:
      - sensor.lichtniveau_keuken
      - sensor.lichtniveau_gang
      - sensor.lichtniveau_werkkamer
      - sensor.lichtniveau_woonkamer
      - sensor.lichtniveau_overloop