homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 6
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  
  customize:
    light.hue_color_lamp_3:
      hidden: true
    media_player.plex_web_firefox:
      hidden: true
    media_player.tablet:
      hidden: true
    media_player.mycroft:
      friendly_name: "Plex woonkamer"
    remote.tv_woonkamer:
      hidden: true
    sensor.power_production:
      hidden: true
    sensor.power_production_normal: 
      hidden: true
    sensor.power_production_low:
      hidden: true
    switch.verwarming_thuis:
      hidden: true
    switch.verwarming_kort_afwezig:
      hidden: true
    switch.verwarming_lang_afwezig:
      hidden: true
    switch.verwarming_comfort:
      hidden: true

zone:
  name: Work
  icon: 'mdi:pi-box'
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  radius: 90

logger:
  default: info
  
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:
  include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

sensor:
  - platform: buienradar
    monitored_conditions:
      - stationname
      - symbol
      - temperature
      - groundtemperature
      - windspeed
      - winddirection
      - precipitation
  - platform: darksky
    api_key: !secret darksky_api
    monitored_conditions:
      - cloud_cover
  - platform: sonarr
    api_key: !secret sonarr_api
    monitored_conditions:
      - upcoming
      - wanted
      - queue
      - diskspace
    days: 28
    unit: TB
  - platform: mqtt
    name: "Verwarming"
    state_topic: "HW/temp/state"
    unit_of_measurement: "°C"
    force_update: true
  - platform: mqtt
    name: "Temperatuur"
    state_topic: "HW/temp/room"
    unit_of_measurement: "°C"
    force_update: true
  - platform: dsmr
    host: 127.0.0.1
    port: 8124
    dsmr_version: 4

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.178.1-64
    interval_seconds: 20
    home_interval: 8
    exclude:
      - 192.168.178.26
      - 192.168.178.30
      - 192.168.178.31

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: !secret mqtt_client_id
  username: !secret mqtt_username
  password: !secret mqtt_password

media_player:
  - platform: plex

weblink:
  entities:
    - name: Router
      url: "http://192.168.178.1"
      icon: "mdi:router-wireless"
    - name: Plex
      url: "http://sherlock:32400"
      icon: "mdi:plex"
    - name: CouchPotato
      url: "http://sherlock:5050"
      icon: "mdi:theater"
    - name: Sonarr
      url: "http://sherlocl:8989"
      icon: "mdi:television-classic"
    - name: uTorrent
      url: "http://sherlock:8082"
      icon: "mdi:download"

light:
  - platform: hue
    host: 192.168.178.23
    allow_unreachable: false
  - platform: mqtt
    name: "Spots keuken"
    command_topic: "HW/sw/0/set"
    state_topic: "HW/sw/0/state"
    brightness_command_topic: "HW/sw/0/dim"
    brightness_state_topic: "HW/sw/0/dim/state"
    brightness_scale: 100
    optimistic: false
  - platform: mqtt
    name: "Lamp eettafel"
    command_topic: "HW/sw/2/set"
    state_topic: "HW/sw/2/state"
    brightness_command_topic: "HW/sw/2/dim"
    brightness_state_topic: "HW/sw/2/dim/state"
    brightness_scale: 100
    optimistic: false
  - platform: mqtt
    name: "Lamp dressoir"
    command_topic: "HW/sw/3/set"
    state_topic: "HW/sw/3/state"
    brightness_command_topic: "HW/sw/3/dim"
    brightness_state_topic: "HW/sw/3/dim/state"
    brightness_scale: 100
    optimistic: false

switch:
  - platform: mqtt
    name: "Boiler keuken"
    command_topic: "HW/sw/1/set"
    state_topic: "HW/sw/1/state"
    optimistic: false
  - platform: mqtt
    name: "Ambilight"
    command_topic: "HW/sw/4/set"
    state_topic: "HW/sw/4/state"
    optimistic: false
  - platform: mqtt
    name: "Verwarming (thuis)"
    command_topic: "HW/temp/set"
    state_topic: "HW/temp/state"
    optimistic: true
    payload_on: "20"
  - platform: mqtt
    name: "Verwarming (kort afwezig)"
    command_topic: "HW/temp/set"
    state_topic: "HW/temp/state"
    optimistic: true
    payload_on: "16"
  - platform: mqtt
    name: "Verwarming (lang afwezig)"
    command_topic: "HW/temp/set"
    state_topic: "HW/temp/state"
    optimistic: true
    payload_on: "12"
  - platform: mqtt
    name: "Verwarming (comfort)"
    command_topic: "HW/temp/set"
    state_topic: "HW/temp/state"
    optimistic: true
    payload_on: "21"

cover:
  - platform: mqtt
    name: "Gordijn voor"
    set_position_topic: "soma/shade/rise201/set"
    state_topic: "soma/shade/rise201/state"
    retain: false
    
remote:
  - platform: harmony
    name: "TV Woonkamer"
    host: 192.168.178.20
    scan_interval: 10

group:
  # By default, every group appears in the HOME tab. 
  # If you create a group default_view it will REPLACE the contents 
  # of the HOME tab so you can customize the HOME tab as you wish.
  kitchen:
    name: Keuken
    entities:
      - light.spots_keuken
      - switch.boiler_keuken
  living_room:
    name: Woonkamer
    entities:
      - light.lamp_tv
      - light.lamp_bank
      - light.lamp_dressoir
      - light.lamp_eettafel
      - switch.ambilight
      - cover.gordijn_voor
      - sensor.verwarming
      - sensor.temperatuur
  people:
    name: People
    entities:
      - device_tracker.huaweip10litefritzbox
  meter_reading:
    name: Meterwaarden
    entities:
      - sensor.power_tariff
      - sensor.power_consumption
      - sensor.power_consumption_low
      - sensor.power_consumption_normal
      - sensor.gas_consumption
      - sensor.hourly_gas_consumption
  sonarr:
    name: Sonarr
    entities:
      - sensor.sonarr_queue
      - sensor.sonarr_disk_space
      - sensor.sonarr_upcoming
      - sensor.sonarr_wanted
  weather:
    name: Weer
    entities:
      - sun.sun
      - sensor.br_wind_speed
      - sensor.br_symbol
      - sensor.br_precipitation
      - sensor.br_wind_direction
      - sensor.br_temperature
      - sensor.br_ground_temperature
      - sensor.br_stationname
      - sensor.dark_sky_cloud_coverage

input_boolean:
  #no initial values, handled by the recorder component
  slapen:
    icon: 'mdi:sleep'

binary_sensor:
  - platform: template
    sensors:
      donker_buiten:
        value_template: >
          {% if (states.sun.sun.attributes.elevation | int < 20) %} 
            true
          {% elif ((states.sun.sun.attributes.elevation | int < 40) and 
            (states.sensor.dark_sky_cloud_coverage.state | int > 50)) %} 
            true
          {% elif (states.sensor.dark_sky_cloud_coverage.state | int > 90) %} 
            true
          {% else %} 
            false
          {% endif %}
        entity_id:
          - sun.sun
          - sensor.dark_sky_cloud_coverage
  - platform: template
    sensors:
      iemand_thuis:
        value_template: >
          {% if (is_state('device_tracker.huaweip10litefritzbox', 'home')) %}
            true
          {% else %} 
            false
          {% endif %}
        entity_id:
          - device_tracker.huaweip10litefritzbox
  - platform: template
    sensors:
      film_kijken:
        value_template: >
          {% if (states.remote.tv_woonkamer.attributes.current_activity | lower == 'watch a movie') %}
            true
          {% else %}
            false
          {% endif %}
        entity_id:
          - remote.tv_woonkamer
  
scene:
  - name: "Slapen"
    entities:
      remote.tv_woonkamer: off
      light.spots_keuken: off
      light.lamp_tv: off
      light.lamp_bank: off
      light.lamp_dressoir: off
      light.lamp_eettafel: off
      switch.ambilight: off
      switch.boiler_keuken: off
      switch.verwarming_kort_afwezig: on
      cover.gordijn_voor:
        position: 90
      input_boolean.slapen: on
  - name: "Opstaan"
    entities:
      cover.gordijn_voor:
        position: 15
      input_boolean.slapen: off
      
  - name: "Verwarming (normaal)"
    entities:
      switch.verwarming_thuis: on
      switch.verwarming_kort_afwezig: off
      switch.verwarming_lang_afwezig: off
      switch.verwarming_comfort: off
  - name: "Verwarming (kort weg)"
    entities:
      switch.verwarming_thuis: off
      switch.verwarming_kort_afwezig: on
      switch.verwarming_lang_afwezig: off
      switch.verwarming_comfort: off
  - name: "Verwarming (lang weg)"
    entities:
      switch.verwarming_thuis: off
      switch.verwarming_kort_afwezig: off
      switch.verwarming_lang_afwezig: on
      switch.verwarming_comfort: off
  - name: "Verwarming (comfort)"
    entities:
      switch.verwarming_thuis: off
      switch.verwarming_kort_afwezig: off
      switch.verwarming_lang_afwezig: off
      switch.verwarming_comfort: on
  
  - name: "Film start"
    entities:
      switch.ambilight: on
  - name: "Film actief"
    entities:
      light.spots_keuken: off
      light.lamp_tv: off
      light.lamp_bank: off
      light.lamp_dressoir: off
      light.lamp_eettafel: off
      switch.ambilight: on
  - name: "Film gepauzeerd"
    entities:
      light.spots_keuken: on
      light.lamp_tv: on
      light.lamp_bank: on
      light.lamp_dressoir: on
      light.lamp_eettafel: on
      switch.ambilight: on

  - name: "Licht normaal"
    entities:
      light.spots_keuken: on
      light.lamp_tv: on
      light.lamp_bank: on
      light.lamp_dressoir: on
      light.lamp_eettafel: on
      switch.ambilight: off

automation: 
  - alias: "Opstaan"
    trigger:
      platform: time
      at: "07:30:00"
    action:
      service: scene.turn_on
      entity_id: scene.opstaan

  - alias: "Lichten aan"
    trigger:
      - platform: state
        entity_id: binary_sensor.donker_buiten
        to: 'on'
      - platform: state
        entity_id: binary_sensor.iemand_thuis
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.iemand_thuis
          state: 'on'
        - condition: state
          entity_id: binary_sensor.donker_buiten
          state: 'on'
        - condition: state
          entity_id: binary_sensor.film_kijken
          state: 'off'
        - condition: state
          entity_id: input_boolean.slapen
          state: 'off'
    action:
      service: scene.turn_on
      entity_id: scene.licht_normaal

  - alias: "Lichten uit"
    trigger:
      - platform: state
        entity_id: binary_sensor.iemand_thuis
        to: 'off'
      - platform: state
        entity_id: binary_sensor.donker_buiten
        state: 'off'
    action:
      service: light.turn_off

  - alias: "Verwarming aan"
    trigger:
      - platform: state
        entity_id: binary_sensor.iemand_thuis
        to: 'on'
      - platform: time
        at: "09:00:00"
    condition:
      condition: and
      conditions:
      - condition: time
        after: "07:00:00"
        before: "22:30:00"
      - condition: state
        entity_id: input_boolean.slapen
        state: 'off'
      - condition: state
        entity_id: binary_sensor.iemand_thuis
        state: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.verwarming_normaal
  
  - alias: "Verwarming laag"
    trigger:
      - platform: state
        entity_id: binary_sensor.iemand_thuis
        to: 'off'
      - platform: time
        at: "22:30:00"
    condition:
      condition: state
      entity_id: switch.verwarming_lang_afwezig
      state: 'off'
    action:
      service: scene.turn_on
      entity_id: scene.verwarming_kort_weg
  
  - alias: "Verwarming uit indien lang niemand thuis"
    trigger:
      platform: state
      entity_id: binary_sensor.iemand_thuis
      to: 'off'
      for:
        hours: 10
    action:
      service: scene.turn_on
      entity_id: scene.verwarming_lang_weg
  
  - alias: "Boiler keuken uit"
    trigger:
      platform: time
      at: "23:59:00"
    action:
      service: switch.turn_off
      entity_id: switch.boiler_keuken
      
  - alias: "Boiler keuken aan (doordeweeks)"
    trigger:
      platform: time
      at: "17:00:00"
    condition: 
      condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      service: switch.turn_on
      entity_id: switch.boiler_keuken
    
  - alias: "Boiler keuken aan (weekend)"
    trigger:
      platform: time
      at: "08:00:00"
    condition: 
      condition: time
      weekday:
        - sat
        - sun
    action:
      service: switch.turn_on
      entity_id: switch.boiler_keuken

  - alias: "Film kijken"
    trigger:
      platform: state
      entity_id: binary_sensor.film_kijken
      to: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.film_start
    
  - alias: "Film gepauzeerd"
    trigger:
      platform: state
      entity_id: media_player.mycroft
      from: "playing"
    condition:
      condition: state
      entity_id: binary_sensor.donker_buiten
      state: 'on'
    action:
      service: scene.turn_on
      entity_id: scene.film_gepauzeerd
    
  - alias: "Film gestart/hervat"
    trigger:
      platform: state
      entity_id: media_player.mycroft
      to: "playing"
    action:
      service: scene.turn_on
      entity_id: scene.film_actief
      
  - alias: "Film gestopt"
    trigger:
      platform: state
      entity_id: binary_sensor.film_kijken
      from: 'on'
      to: 'off'
    condition:
      condition: state
      entity_id: binary_sensor.donker_buiten
      state: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.licht_normaal
  
  - alias: "Gordijn omlaag in namiddag"
    trigger:
      platform: time
      at: "17:00:00"
    action:
      service: cover.set_cover_position
      data:
        entity_id: cover.gordijn_voor
        position: 50