- platform: hue
  host: 192.168.178.23
  allow_unreachable: false
  
- platform: mqtt
  name: "Spots keuken"
  command_topic: "HW/sw/0/set"
  state_topic: "HW/sw/0/state"
  brightness_command_topic: "HW/sw/0/dim"
  brightness_state_topic: "HW/sw/0/dim/state"
  brightness_scale: 100
  optimistic: false
  
- platform: mqtt
  name: "Lamp eettafel"
  command_topic: "HW/sw/2/set"
  state_topic: "HW/sw/2/state"
  brightness_command_topic: "HW/sw/2/dim"
  brightness_state_topic: "HW/sw/2/dim/state"
  brightness_scale: 100
  optimistic: false
  
- platform: mqtt
  name: "Lamp dressoir"
  command_topic: "HW/sw/3/set"
  state_topic: "HW/sw/3/state"
  brightness_command_topic: "HW/sw/3/dim"
  brightness_state_topic: "HW/sw/3/dim/state"
  brightness_scale: 100
  optimistic: false