- platform: buienradar
  monitored_conditions:
    - stationname
    - symbol
    - temperature
    - groundtemperature
    - windspeed
    - winddirection
    - precipitation
    - irradiance
    
- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - cloud_cover

- platform: mqtt
  name: "Sonarr"
  state_topic: "downloads/sonarr"

- platform: mqtt
  name: "Radarr"
  state_topic: "downloads/radarr"

- platform: template
  sensors:
    current_time:
      value_template: '{{ now().strftime("%H%M") }}'

- platform: template
  sensors:
    positie_gordijn:
      friendly_name: "Gewenste positie gordijn"
      value_template: >
        {% if (is_state("input_boolean.slapen", "on")) %}
          90
        {% else %}
          {% if (
            states.sensor.current_time.state | int >= 2000 or 
            states.sensor.current_time.state | int < 700) 
          %}
            70
          {% elif (states.sensor.current_time.state | int >= 1800) %}
            60
          {% else %}
            {% if (
              states.climate.toon_van_eneco.attributes.current_temperature | int >= 21 and
              states.sensor.br_irradiance.state | int >= 300
            ) %}
              60
            {% else %}
              15
            {% endif %}
          {% endif %}
        {% endif %}

- platform: template
  sensors:
    above_cloud_lux:
      friendly_name: "Above Cloud Lux"
      unit_of_measurement: "Lux"
      value_template: '{{ states.sun.sun.attributes.daylight | round(0) }}'
    exterior_lux:
      friendly_name: "Exterior Lux"
      unit_of_measurement: "lux"
      value_template: '{{ ((100.1-states.sensor.dark_sky_cloud_coverage.state|float)/100 * states.sun.sun.attributes.daylight) | round(0) }}'

- platform: template
  sensors:
    current_temperature_toon:
      friendly_name: "Temperatuur Toon"
      unit_of_measurement: '째C'
      value_template: '{{ states.climate.toon_van_eneco.attributes.current_temperature }}'
      
- platform: rest
  resource: !secret hue_temperature_keuken
  value_template: '{{ value_json.config.battery }}'
  unit_of_measurement: '%'
  name: 'Batterij Hue keuken'
  scan_interval: 3600
  
- platform: rest
  resource: !secret hue_temperature_keuken
  value_template: '{{ (value_json.state.temperature - 78) | float / 100 }}'
  unit_of_measurement: '째C'
  name: 'Temperatuur keuken'

- platform: rest
  resource: !secret hue_presence_keuken
  value_template: '{{ value_json.state.presence }}'
  name: 'Beweging keuken'
  scan_interval: 2

- platform: rest
  resource: !secret hue_lightlevel_keuken
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Lichtniveau keuken'

- platform: rest
  resource: !secret hue_temperature_werkkamer
  value_template: '{{ value_json.config.battery }}'
  unit_of_measurement: '%'
  name: 'Batterij Hue werkkamer'
  scan_interval: 3600
  
- platform: rest
  resource: !secret hue_temperature_werkkamer
  value_template: '{{ (value_json.state.temperature + 26) | float / 100 }}'
  unit_of_measurement: '째C'
  name: 'Temperatuur werkkamer'

- platform: rest
  resource: !secret hue_presence_werkkamer
  value_template: '{{ value_json.state.presence }}'
  name: 'Beweging werkkamer'
  scan_interval: 2

- platform: rest
  resource: !secret hue_lightlevel_werkkamer
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Lichtniveau werkkamer'

- platform: rest
  resource: !secret hue_temperature_gang
  value_template: '{{ value_json.config.battery }}'
  unit_of_measurement: '%'
  name: 'Batterij Hue gang'
  scan_interval: 3600
  
- platform: rest
  resource: !secret hue_temperature_gang
  value_template: '{{ (value_json.state.temperature - 182) | float / 100 }}'
  unit_of_measurement: '째C'
  name: 'Temperatuur gang'

- platform: rest
  resource: !secret hue_presence_gang
  value_template: '{{ value_json.state.presence }}'
  name: 'Beweging gang'
  scan_interval: 1

- platform: rest
  resource: !secret hue_lightlevel_gang
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Lichtniveau gang'