- platform: buienradar
  monitored_conditions:
    - stationname
    - symbol
    - temperature
    - groundtemperature
    - windspeed
    - winddirection
    - precipitation
    - irradiance
    
- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - cloud_cover

- platform: template
  sensors:
    current_time:
      value_template: '{{ now().strftime("%H%M") }}'

- platform: template
  sensors:
    above_cloud_lux:
      friendly_name: "Above Cloud Lux"
      unit_of_measurement: "Lux"
      value_template: '{{ states.sun.sun.attributes.daylight | round(0) }}'
    exterior_lux:
      friendly_name: "Exterior Lux"
      unit_of_measurement: "Lux"
      value_template: '{{ ((100.1-states.sensor.dark_sky_cloud_coverage.state|float)/100 * states.sun.sun.attributes.daylight) | round(0) }}'
 
- platform: rest
  resource: !secret hue_temperature_keuken
  value_template: '{{ value_json.config.battery }}'
  unit_of_measurement: '%'
  name: 'Batterij Hue keuken'
  scan_interval: 3600
  
- platform: rest
  resource: !secret hue_temperature_keuken
  value_template: '{{ (value_json.state.temperature - 78) | float / 100 }}'
  unit_of_measurement: '°C'
  name: 'Temperatuur keuken'

- platform: rest
  resource: !secret hue_lightlevel_keuken
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Lichtniveau keuken'

- platform: rest
  resource: !secret hue_temperature_werkkamer
  value_template: '{{ value_json.config.battery }}'
  unit_of_measurement: '%'
  name: 'Batterij Hue werkkamer'
  scan_interval: 3600
  
- platform: rest
  resource: !secret hue_temperature_werkkamer
  value_template: '{{ (value_json.state.temperature + 26) | float / 100 }}'
  unit_of_measurement: '°C'
  name: 'Temperatuur werkkamer'

- platform: rest
  resource: !secret hue_lightlevel_werkkamer
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Lichtniveau werkkamer'

- platform: rest
  resource: !secret hue_temperature_gang
  value_template: '{{ value_json.config.battery }}'
  unit_of_measurement: '%'
  name: 'Batterij Hue gang'
  scan_interval: 3600
  
- platform: rest
  resource: !secret hue_temperature_gang
  value_template: '{{ (value_json.state.temperature - 212) | float / 100 }}'
  unit_of_measurement: '°C'
  name: 'Temperatuur gang'

- platform: rest
  resource: !secret hue_lightlevel_gang
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Lichtniveau gang'

- platform: rest
  resource: !secret hue_temperature_woonkamer
  value_template: '{{ value_json.config.battery }}'
  unit_of_measurement: '%'
  name: 'Batterij Hue woonkamer'
  scan_interval: 3600
  
- platform: rest
  resource: !secret hue_temperature_woonkamer
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: '°C'
  name: 'Temperatuur woonkamer'

- platform: rest
  resource: !secret hue_lightlevel_woonkamer
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Lichtniveau woonkamer'

- platform: rest
  resource: !secret hue_temperature_overloop
  value_template: '{{ value_json.config.battery }}'
  unit_of_measurement: '%'
  name: 'Batterij Hue overloop'
  scan_interval: 3600
  
- platform: rest
  resource: !secret hue_temperature_overloop
  value_template: '{{ (value_json.state.temperature + 115) | float / 100 }}'
  unit_of_measurement: '°C'
  name: 'Temperatuur overloop'

- platform: rest
  resource: !secret hue_lightlevel_overloop
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Lichtniveau overloop'