- platform: buienradar
  monitored_conditions:
    - stationname
    - symbol
    - temperature
    - groundtemperature
    - windspeed
    - winddirection
    - precipitation
    - irradiance

- platform: template
  sensors:
    current_time:
      value_template: '{{ now().strftime("%H%M") }}'

- platform: rest
  resource: !secret hue_temperature_keuken
  value_template: '{{ value_json.config.battery }}'
  unit_of_measurement: '%'
  name: 'Batterij Hue keuken'
  scan_interval: 3600
  
- platform: rest
  resource: !secret hue_temperature_keuken
  value_template: '{{ (value_json.state.temperature + 167) | float / 100 }}'
  unit_of_measurement: '°C'
  name: 'Temperatuur keuken'

- platform: rest
  resource: !secret hue_lightlevel_keuken
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Lichtniveau keuken'
  scan_interval: 30

- platform: rest
  resource: !secret hue_temperature_werkkamer
  value_template: '{{ value_json.config.battery }}'
  unit_of_measurement: '%'
  name: 'Batterij Hue werkkamer'
  scan_interval: 3600
  
- platform: rest
  resource: !secret hue_temperature_werkkamer
  value_template: '{{ (value_json.state.temperature + 31) | float / 100 }}'
  unit_of_measurement: '°C'
  name: 'Temperatuur werkkamer'

- platform: rest
  resource: !secret hue_lightlevel_werkkamer
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Lichtniveau werkkamer'

- platform: rest
  resource: !secret hue_temperature_gang
  value_template: '{{ value_json.config.battery }}'
  unit_of_measurement: '%'
  name: 'Batterij Hue gang'
  scan_interval: 3600
  
- platform: rest
  resource: !secret hue_temperature_gang
  value_template: '{{ (value_json.state.temperature - 12) | float / 100 }}'
  unit_of_measurement: '°C'
  name: 'Temperatuur gang'

- platform: rest
  resource: !secret hue_lightlevel_gang
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Lichtniveau gang'

- platform: rest
  resource: !secret hue_temperature_woonkamer
  value_template: '{{ value_json.config.battery }}'
  unit_of_measurement: '%'
  name: 'Batterij Hue woonkamer'
  scan_interval: 3600
  
- platform: rest
  resource: !secret hue_temperature_woonkamer
  value_template: '{{ (value_json.state.temperature + 233) | float / 100 }}'
  unit_of_measurement: '°C'
  name: 'Temperatuur woonkamer'

- platform: rest
  resource: !secret hue_lightlevel_woonkamer
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Lichtniveau woonkamer'

- platform: rest
  resource: !secret hue_temperature_overloop
  value_template: '{{ value_json.config.battery }}'
  unit_of_measurement: '%'
  name: 'Batterij Hue overloop'
  scan_interval: 3600
  
- platform: rest
  resource: !secret hue_temperature_overloop
  value_template: '{{ (value_json.state.temperature + 177 ) | float / 100 }}'
  unit_of_measurement: '°C'
  name: 'Temperatuur overloop'

- platform: rest
  resource: !secret hue_lightlevel_overloop
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Lichtniveau overloop'
