- platform: buienradar
  monitored_conditions:
    - stationname
    - symbol
    - temperature
    - groundtemperature
    - windspeed
    - winddirection
    - precipitation
    - irradiance
    
- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - cloud_cover
  
- platform: mqtt
  name: "Verwarming"
  state_topic: "HW/temp/state"
  unit_of_measurement: "°C"
  force_update: true
  
- platform: mqtt
  name: "Temperatuur"
  state_topic: "HW/temp/room"
  unit_of_measurement: "°C"

- platform: mqtt
  name: "Sonarr"
  state_topic: "downloads/sonarr"

- platform: mqtt
  name: "CouchPotato"
  state_topic: "downloads/couchpotato"
  
- platform: dsmr
  host: 127.0.0.1
  port: 8124
  dsmr_version: 4

- platform: template
  sensors:
    current_time:
      value_template: '{{ now().strftime("%H%M") }}'

- platform: template
  sensors:
    positie_gordijn:
      friendly_name: "Gewenste positie gordijn"
      value_template: >
        {% if (is_state("input_boolean.slapen", "on")) %}
          90
        {% else %}
          {% if (
            states.sensor.current_time.state | int >= 2000 or 
            states.sensor.current_time.state | int < 700) 
          %}
            70
          {% elif (states.sensor.current_time.state | int >= 1800) %}
            60
          {% else %}
            {% if (
              states.sensor.temperatuur.state | int >= 21 and
              states.sensor.br_irradiance.state | int >= 300
            ) %}
              60
            {% else %}
              15
            {% endif %}
          {% endif %}
        {% endif %}

- platform: template
  sensors:
    verschil_positie_gordijn:
      friendly_name: "Verschil positie gordijn"
      value_template: '{{ (states.sensor.positie_gordijn.state | int - states.cover.gordijn_voor.attributes.current_position | int) | abs }}'