- platform: mqtt
  name: "Boiler keuken"
  command_topic: "HW/sw/1/set"
  state_topic: "HW/sw/1/state"
  optimistic: false
  
- platform: mqtt
  name: "Ambilight"
  command_topic: "HW/sw/4/set"
  state_topic: "HW/sw/4/state"
  optimistic: false
  