input_boolean:
  activity_sleeping:
    icon: mdi:sleep
  activity_videocall:
    icon: mdi:camera-front-variant

binary_sensor:
- platform: tod
  name: activity_bedtijd
  after: '00:00'
  before: '07:30'

- platform: tod
  name: activity_werktijd
  after: '09:00'
  before: '17:30'

- platform: template
  sensors:
    activity_thuiswerken:
      friendly_name: Thuiswerken
      value_template: >
        {% if 
          is_state('binary_sensor.workday_sensor', 'on') and
          is_state('binary_sensor.activity_werktijd', 'on') and 
          is_state('binary_sensor.presence_iemand_thuis', 'on')
        %}
          true
        {% else %} 
          false
        {% endif %}

homeassistant:
  customize:
    input_boolean.activity_sleeping:
      friendly_name: Slapen
    input_boolean.activity_videocall:
      friendly_name: Videocall
    binary_sensor.activity_bedtijd:
      friendly_name: Bedtijd
    binary_sensor.activity_werktijd:
      friendly_name: Werktijd

automation:
- id: activity_wakingup
  alias: Opstaan
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.activity_bedtijd
    to: 'off'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.activity_sleeping

- id: activity_sleeping
  alias: Slapen
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: tradfri_remote_control
      event: 1002
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.activity_sleeping
