template:
- trigger:
  - platform: state
    entity_id: sensor.current_power_usage
  
  sensor:
  - unique_id: power_todays_consumption_overig
    name: Overig Today's Consumption
    unit_of_measurement: 'kWh'
    device_class: energy
    state_class: total
    state: >
      {%- set ns = namespace(states=[]) -%}
      {%- for s in states.sensor -%}
      {%- if s.object_id.endswith('_today_s_consumption') and not s.object_id.startswith('overig_') -%}
      {%- set ns.states = ns.states + [ s.state | float(default=0) ] -%}
      {%- endif -%}
      {%- endfor -%}
      {{ (states('sensor.energy_usage_today') | float(default=0) - (ns.states | sum)) | round(3)}}
    
  - unique_id: power_current_consumption_overig
    name: Overig Current Consumption
    unit_of_measurement: 'W'
    device_class: energy
    state_class: measurement
    state: >
      {%- set ns = namespace(states=[]) -%}
      {%- for s in states.sensor -%}
      {%- if s.object_id.endswith('_current_consumption') and not s.object_id.startswith('overig_') -%}
      {%- set ns.states = ns.states + [ s.state | float(default=0) ] -%}
      {%- endif -%}
      {%- endfor -%}
      {{ (states('sensor.current_power_usage') | float(default=0) - (ns.states | sum)) | round(3)}}

shell_command:
  turn_off_watson: !secret watson_shutdown

automation:
- id: bureau_off
  alias: Apparatuur bureau uitschakelen
  initial_state: on
  trigger:
    platform: state
    entity_id: input_boolean.activity_sleeping
    to: 'on'
  action:
    service: switch.turn_off
    entity_id: switch.bureau

- id: bureau_on
  alias: Apparatuur bureau inschakelen
  initial_state: on
  trigger:
    platform: state
    entity_id: input_boolean.activity_sleeping
    to: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.bureau

- id: tv_off
  alias: Apparatuur tv uitschakelen
  initial_state: on
  trigger:
    platform: state
    entity_id: input_boolean.activity_sleeping
    to: 'on'
  action:
  - service: shell_command.turn_off_watson
  - service: switch.turn_off
    entity_id: switch.tv_meubel

- id: tv_on
  alias: Apparatuur tv inschakelen
  initial_state: on
  trigger:
    platform: state
    entity_id: input_boolean.activity_sleeping
    to: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.tv_meubel
