switch:
- platform: mystrom
  name: washing_machine
  host: 192.168.178.57

sensor:
- platform: template
  sensors:
    washing_machine_usage:
      friendly_name: Stroomgebruik wasmachine
      unit_of_measurement: W
      value_template: >
        {{ state_attr('switch.washing_machine', 'current_power_w') }}

binary_sensor:
- platform: template
  sensors:
    washing_machine_running:
      friendly_name: Wasmachine bezig
      delay_on:
        minutes: 5
      delay_off:
        minutes: 5
      value_template: >
        {{ states('sensor.washing_machine_usage')|float > 10 }}

homeassistant:
  customize:
    switch.washing_machine:
      friendly_name: Wasmachine

automation:
- id: washing_machine_ready_notification
  alias: Wasmachine klaar notification
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.washing_machine_running
    from: 'on'
    to: 'off'
  action:
  - service: notify.telegram
    data:
      message: 'De wasmachine is klaar!'